**1. Consider the two-dimensional array, arr2d**

`arr2d = np.array([[1, 2, 3],[4,5,6,],[7,8,9]])`

In [1]:
import numpy as np

In [32]:
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print("arr2d:\n", arr2d)
print()

# display the last column
print("Display the last column:\n", arr2d[:, -1].reshape(3, 1))
print()

# last 2 elements of middle array
print("Last 2 elements of middle array: ", arr2d[1, 1:])
print()

# display 1-D array of the elements in arr2d that <= 4
print("arr2d<=4:\n", arr2d<=4)  # decide whether element is <=4 (true or false)
print()
print("array[arr2d<=4]:\n", arr2d[arr2d<=4])  # display the elements in 1-D array

arr2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Display the last column:
 [[3]
 [6]
 [9]]

Last 2 elements of middle array:  [5 6]

arr2d<=4:
 [[ True  True  True]
 [ True False False]
 [False False False]]

array[arr2d<=4]:
 [1 2 3 4]


**2. 製作一層的NN網路以及老師介紹到的 Activation Function**

In [36]:
input = np.array([[0.5, 0.11, 0.32],[0.14, 0.52, 0.68],[0.59, 0.45, 0.30]])
print("input:\n", input)
print()
weights = np.random.rand(1, 3)
print("weight:\n", weights)
bias = np.random.rand(1, 1)
print("bias:\n", bias)

input:
 [[0.5  0.11 0.32]
 [0.14 0.52 0.68]
 [0.59 0.45 0.3 ]]

weight:
 [[0.6068056  0.3825413  0.34349951]]
bias:
 [[0.52564579]]


In [37]:
def sigmoid (x):  # activation function
    return np.exp(x) / (1 + np.exp(x))

In [38]:
output = sigmoid(np.dot(weights, input) + bias)
print("output:\n", output)

output:
 [[0.74748981 0.72028801 0.74706157]]
